name: CI - Deploy to sa-lab.dev
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      # debug
      - name: Checkout sources
        run: |
            echo test debug
            echo "test debug"
            echo "${{ secrets.FTP_SERVER }}"
            echo "${{ secrets.FTP_USERNAME }}"
            echo "${{ secrets.FTP_PASSWORD }}"

      # Here is the deployment action
      - name: Upload bundle via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        # uses: airvzxf/ftp-deployment-action@v2
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./docs"
          server-dir: "/docs"
          # remote_dir: "/docs"
          # delete: "true"
          # ftp_ssl_allow: "false"
